[build]
  command = "node build.js"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[headers]]
  for = "/uv/uv.sw.js"
  [headers.values]
    Service-Worker-Allowed = "/"
